import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";

import Betting from "@/components/Betting";

const inter = Inter({ subsets: ["latin"] });
// const Betting = dynamic(
//   // typescript에서 props를 전달할때 interface를 정의해줍니다.
//   () => import("@/components/Betting"), // Component로 사용할 항목을 import합니다.
//   { ssr: false } // ssr옵션을 false로 설정해줍니다.
// );

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Betting />
      </main>
    </>
  );
}
